In [1]:
from uu import encode

from sklearn.preprocessing import LabelEncoder, OneHotEncoder

## 标签编码

In [4]:
data = ["小学", "本科", "中学", "大学", "硕士", "博士"]

In [5]:
encoder = LabelEncoder()
data = encoder.fit_transform(data)  # 默认是安装字母表
print(data)

[3 4 0 2 5 1]


## 独热编码

In [11]:
import numpy as np

data = np.array(["red", "yellow", "green", "red", "red", "yellow"]).reshape(-1, 1)
encoder = OneHotEncoder(sparse_output=False)
data = encoder.fit_transform(data)
print(data)

[[0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
