# 创建ndarray数组方式

In [3]:
import numpy as np

arr1 = np.zeros((2,3))
# 在Jupyter中也可以直接书写要呈现的对象名称 不需要加print 直接运行 打印内容
arr1

array([[0., 0., 0.],
       [0., 0., 0.]])

In [4]:
arr2 = np.ones((2,3)) # 创建2行3列的 全为1的数组 类型为浮点类型 float64
arr2

array([[1., 1., 1.],
       [1., 1., 1.]])

In [8]:
arr3 = np.empty((3,4))
arr3

array([[6.23042070e-307, 1.89146896e-307, 1.37961302e-306,
        6.23053614e-307],
       [1.69121639e-306, 1.00137236e-307, 1.05695337e-307,
        1.11258854e-306],
       [1.11261502e-306, 1.42410839e-306, 7.56597770e-307,
        2.44032786e-312]])

In [9]:
# 根据指定的数组 生成相同形状的数组
a1 = np.zeros_like(arr1)
a1

array([[0., 0., 0.],
       [0., 0., 0.]])

In [10]:
# 根据指定的数组 生成相同形状的数组
a2 = np.ones_like(arr2)
a2

array([[1., 1., 1.],
       [1., 1., 1.]])

In [11]:
# 根据指定的数组 生成相同形状的数组
a3 = np.empty_like(arr3)
a3

array([[6.23042070e-307, 1.89146896e-307, 1.37961302e-306,
        6.23053614e-307],
       [1.69121639e-306, 1.00137236e-307, 1.05695337e-307,
        1.11258854e-306],
       [1.11261502e-306, 1.42410839e-306, 7.56597770e-307,
        2.44032786e-312]])