# 创建ndarray的方式

In [1]:
import numpy as np

# 指定形状 和 数据 填充数组
a1 = np.full((2,4),555)

a1

array([[555, 555, 555, 555],
       [555, 555, 555, 555]])

In [2]:
# 根据传入的数组 和 指定的数据 填充数组
a2 = np.full_like(a1,5)
a2

array([[5, 5, 5, 5],
       [5, 5, 5, 5]])

In [3]:
# 根据指定的起始和结束 间隔 生成数组元素
a3 = np.arange(0,10,2)
a3

array([0, 2, 4, 6, 8])

In [4]:
# 生成等差数列

a4 =  np.linspace(0,10,3)
a4


array([ 0.,  5., 10.])

In [5]:
#endpoint = False 表示不包含最终值
a5 =  np.linspace(0,10,3,endpoint=False)
a5

array([0.        , 3.33333333, 6.66666667])

In [6]:
# 生成等比数列

a6 = np.logspace(start=1,stop=5,num=5,base=2)
a6

array([ 2.,  4.,  8., 16., 32.])

In [8]:
# 上方的等比 相当于如下操作
a7 = np.linspace(start=1,stop=5,num=5)
print(a7)
print(2 ** a7)

[1. 2. 3. 4. 5.]
[ 2.  4.  8. 16. 32.]
