# 创建ndarray的方式

In [1]:
import numpy as np

# 创建给定形状的数组 数据属于0~1之间的随机小数
a1 = np.random.rand(2,3)
a1


array([[0.47425006, 0.19858263, 0.18343844],
       [0.36613879, 0.55576829, 0.04241566]])

In [10]:
# 随机整数 1 ~ 10 之间  3行2列
a2 = np.random.randint(1,10,(3,2))
a2

array([[3, 2],
       [4, 3],
       [2, 6]], dtype=int32)

In [11]:
# 随机小数 3 ~ 6 之间  3行3列
a3 = np.random.uniform(3,6,(3,3))
a3

array([[4.08760501, 5.29270202, 4.34950939],
       [3.05163163, 3.61061267, 3.55902515],
       [3.06839731, 4.76732422, 4.98344093]])

In [12]:
# 返回给定形状的数组，用标准正态分布(均值为0，标准差为1)的随机样本填充。
# 2行3列
a4 = np.random.randn(2,3)
a4

array([[ 0.58290516,  0.41597849,  0.24035946],
       [-0.88002408,  0.3782257 , -0.66748084]])