# ndarray数据类型

In [1]:
import numpy as np


arr1 = np.array([1,2,3],dtype=float)
arr1

array([1., 2., 3.])

In [2]:
arr2 = np.array([1.5,2,3.6,5.5],dtype=int)
arr2

array([1, 2, 3, 5])

In [4]:
# u1 表示无符号1字节的整数 不允许有负数
arr3 = np.array([1,2,3,-4],dtype="u1")
arr3

OverflowError: Python integer -4 out of bounds for uint8

In [7]:
# 如果数组中的数据类型不一致 numpy会自动向上兼容为一致的类型
# 这里全部兼容为字符串类型
arr4 = np.array([1,2,3,4.5,"abc"])
arr4.dtype

dtype('<U32')

In [9]:
arr5 = np.array([1,2,3,4,True,False,0,None,""],dtype="?")
arr5

array([ True,  True,  True,  True,  True, False, False, False, False])