# 切片操作 用法和之前一致

In [1]:
import numpy as np

# 生成0~9序列填充数组
arr1 = np.arange(10)
arr1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [2]:
print(arr1[2]) # 使用下标访问

2


In [3]:
print(arr1[1:3]) # 包前不包后

[1 2]


In [4]:
print(arr1[2:]) # 从指定位置开始到最后

[2 3 4 5 6 7 8 9]


In [5]:
print(arr1[2:9:2]) # 指定起始和结束 以及 步长

[2 4 6 8]


In [6]:
print(arr1[slice(2,9,2)]) # 效果跟上方一致

[2 4 6 8]
