# 常用函数


In [1]:
import numpy as np

arr1 = np.array([1,2,3,4,-5,-6])

arr1

array([ 1,  2,  3,  4, -5, -6])

In [2]:
np.abs(arr1)

array([1, 2, 3, 4, 5, 6])

In [3]:
arr2 = np.array([1.5,2.3,3.6,4,-5,-6])
# 向上取整
np.ceil(arr2)


array([ 2.,  3.,  4.,  4., -5., -6.])

In [4]:
arr2 = np.array([1.5,2.3,3.6,4,-5,-6])

np.floor(arr2) # 向下取整


array([ 1.,  2.,  3.,  4., -5., -6.])

In [5]:
arr2 = np.array([1.5,2.3,3.6,4,-5,-6])
np.rint(arr2) # 四舍五入

array([ 2.,  2.,  4.,  4., -5., -6.])

In [12]:
arr2 = np.array([1.5,2.3,3.6,4,-5,-6])


np.isnan(arr2) # NaN not a number 不是一个数字为True 是的话为False



array([False, False, False, False, False, False])

In [13]:
arr2 = np.array(["a","b","c","d","e","f","g"])
np.isnan(arr2) # 类型不匹配

TypeError: ufunc 'isnan' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''

In [14]:
arr3 = np.array([1,2,3,4])
np.multiply(arr3,2) # 乘法计算 数组中的每个元素都与指定的数据相乘

array([2, 4, 6, 8])

In [15]:
arr3 = np.array([1,2,3,4])
np.divide(arr3,2) # 除法计算 数组中的每个元素都与指定的数据相除


array([0.5, 1. , 1.5, 2. ])

In [16]:
arr3 = np.array([1,2,3,4])
arr4 = np.array([1,2,3,4])
np.divide(arr3,arr4) # 对位计算


array([1., 1., 1., 1.])

In [17]:
arr3 = np.array([1,2,3,4])
arr4 = np.array([1,2,3,4])
np.multiply(arr3,arr4) # 对位计算

array([ 1,  4,  9, 16])

In [18]:
arr3 = np.array([1,2,3,4])

np.where(arr3 > 2 , "ok" , "error")

array(['error', 'error', 'ok', 'ok'], dtype='<U5')