# 统计函数

In [14]:
import numpy as np

arr1 = np.array([[1,2,3,8],[7,4,5,6]])

arr1

array([[1, 2, 3, 8],
       [7, 4, 5, 6]])

In [7]:
print(np.mean(arr1)) # 平均值

3.5


In [8]:
print(np.sum(arr1)) # 求和

21


In [9]:
print(np.max(arr1)) # 最大值

6


In [10]:
print(np.min(arr1)) # 最小值

1


In [11]:
print(np.var(arr1))  # 方差

2.9166666666666665


In [12]:
print(np.std(arr1))  # 标准差

1.707825127659933


In [15]:
print(np.argmax(arr1))  #获取最大值的下标

3


In [16]:
print(np.argmin(arr1))  # 获取最小值下标

0


In [18]:
arr1 = np.array([[1,2,3,8],[7,4,5,6]])
print(np.cumsum(arr1)) # 将数组展平以后 求累计和

[ 1  3  6 14 21 25 30 36]


In [19]:
arr1 = np.array([[1,2,3,8],[7,4,5,6]])
print(np.cumprod(arr1)) # 将数组展平以后 求累计乘积

[    1     2     6    48   336  1344  6720 40320]
