# 排序函数

In [1]:
import numpy as np


arr1 = np.random.randint(0,10,(3,3))
arr1

array([[6, 3, 3],
       [0, 7, 2],
       [2, 5, 6]], dtype=int32)

In [2]:
arr1.sort() # 从每行内部 从左到右排序
arr1

array([[3, 3, 6],
       [0, 2, 7],
       [2, 5, 6]], dtype=int32)

In [3]:
arr1.sort(axis=0)
arr1

array([[0, 2, 6],
       [2, 3, 6],
       [3, 5, 7]], dtype=int32)