In [2]:
import torch
from mpmath.tests.test_elliptic import zero

## 1. 基于内容创建张量

In [4]:
# 传入一个标量
t1 = torch.tensor(1)
print(t1)
print(t1.shape)

tensor(1)
torch.Size([])


In [5]:
# 传入一个列表
t1 = torch.tensor([1, 2])
print(t1)
print(t1.shape)

tensor([1, 2])
torch.Size([2])


In [6]:
# 传入一二维列表
t1 = torch.tensor([ [10, 20], [30, 40] ])
print(t1)
print(t1.shape)

tensor([[10, 20],
        [30, 40]])
torch.Size([2, 2])


In [10]:
# 传入高维数组
t1 = torch.tensor([ [[10, 20, 10], [30, 40, 30]],  [[10, 20, 40], [30, 40, 50]]])
print(t1)
print(t1.shape)

tensor([[[10, 20, 10],
         [30, 40, 30]],

        [[10, 20, 40],
         [30, 40, 50]]])
torch.Size([2, 2, 3])


In [11]:
# 传入numpy的ndarry
import numpy as np
t1 = torch.tensor(np.array([[10, 20, 10], [30, 40, 30]]))
print(t1)
print(t1.shape)

tensor([[10, 20, 10],
        [30, 40, 30]])
torch.Size([2, 3])


In [15]:
# 数据类型:  基于内存创建的tensor, 数据类型默认是保持与传入的内容不变
t1 = torch.tensor([1, 2], dtype=torch.float)
print(t1.dtype)

torch.float32


## 2. 基于形状创建tensor


In [18]:
t1 = torch.Tensor(2, 3, 4)
print(t1)
print(t1.shape)
print(t1.dtype)

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])
torch.Size([2, 3, 4])
torch.float32


## 3. 创建指定类型的张量


In [20]:
t1 = torch.LongTensor(2,3)
print(t1)
print(t1.dtype)
print(t1.shape)

tensor([[0, 0, 0],
        [0, 0, 0]])
torch.int64
torch.Size([2, 3])


In [21]:
t1 = torch.IntTensor(2,3)
print(t1)
print(t1.dtype)
print(t1.shape)

tensor([[0, 0, 0],
        [0, 0, 0]], dtype=torch.int32)
torch.int32
torch.Size([2, 3])


In [22]:
t1 = torch.ShortTensor(2,3)
print(t1)
print(t1.dtype)
print(t1.shape)

tensor([[0, 0, 0],
        [0, 0, 0]], dtype=torch.int16)
torch.int16
torch.Size([2, 3])


In [23]:
t1 = torch.ByteTensor(2,3)
print(t1)
print(t1.dtype)
print(t1.shape)

tensor([[0, 0, 0],
        [0, 0, 0]], dtype=torch.uint8)
torch.uint8
torch.Size([2, 3])


In [24]:
t1 = torch.FloatTensor(2,3)
print(t1)
print(t1.dtype)
print(t1.shape)

tensor([[0., 0., 0.],
        [0., 0., 0.]])
torch.float32
torch.Size([2, 3])


In [25]:
t1 = torch.DoubleTensor(2,3)
print(t1)
print(t1.dtype)
print(t1.shape)

tensor([[0., 0., 0.],
        [0., 0., 0.]], dtype=torch.float64)
torch.float64
torch.Size([2, 3])


In [26]:
t1 = torch.HalfTensor(2,3)
print(t1)
print(t1.dtype)
print(t1.shape)

tensor([[0., 0., 0.],
        [0., 0., 0.]], dtype=torch.float16)
torch.float16
torch.Size([2, 3])


In [27]:
t1 = torch.BoolTensor(2,3)
print(t1)
print(t1.dtype)
print(t1.shape)

tensor([[False, False, False],
        [False, False, False]])
torch.bool
torch.Size([2, 3])


## 4. 根据数据区间创建张量

In [30]:
# [start, end)
t1 = torch.arange(start=10, end=100, step=10)
print(t1)
print(t1.shape)

tensor([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100])
torch.Size([10])


In [34]:
# [start, end]
t1 = torch.linspace(10, 100, 5)  # step = (end - start)/ (steps - 1)
print(t1)
print(t1.shape)

tensor([ 10.0000,  32.5000,  55.0000,  77.5000, 100.0000])
torch.Size([5])


In [36]:
t1 = torch.logspace(1, 3, 4)  # 10^1 10^2 10^3
print(t1)
print(t1.shape)


tensor([  10.0000,   46.4159,  215.4435, 1000.0000])
torch.Size([4])


In [38]:
t1 = torch.logspace(1, 3, 4, base=np.e)  # 10^1 10^2 10^3
print(t1)
print(t1.shape)

tensor([ 2.7183,  5.2945, 10.3123, 20.0855])
torch.Size([4])


## 5. 根据填充创建张量


In [41]:
t1 = torch.ones(3, 4, 5)
print(t1)

tensor([[[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]]])


In [43]:
t2 = torch.ones_like(t1)
print(t2)

tensor([[[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]]])


In [44]:
t1 = torch.zeros(2,3)
print(t1)

tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [52]:
t1 = torch.empty(2,3)
print(t1)

tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [53]:
t1 = torch.full((2,3), fill_value=20)
print(t1)

tensor([[20, 20, 20],
        [20, 20, 20]])


In [54]:
t1 = torch.eye(3)
print(t1)

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])


In [55]:
t1 = torch.eye(3, 4)
print(t1)

tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.]])


## 创建随机张量

In [65]:
# 均匀分布:  [0, 1)
t1 = torch.rand(2,3)
print(t1)

tensor([[0.7880, 0.2562, 0.6256],
        [0.7174, 0.8481, 0.6091]])


In [71]:
# 均匀分布
t1 = torch.randint(2, 10, (2,3))
print(t1)

tensor([[2, 5, 2],
        [8, 6, 5]])


In [74]:
# 标准正态分布
t1 = torch.randn(2, 3)
print(t1)

tensor([[-0.7886,  0.2617, -0.6211],
        [-0.3120, -1.6339, -0.0060]])


In [75]:
# 正态分布
t1 = torch.normal(5, 1, (2,3))
print(t1)

tensor([[3.5356, 5.3648, 2.1082],
        [5.8913, 5.2143, 4.7700]])


In [91]:
# 洗牌  [0, 10) 随机排序
t1 = torch.randperm(10)
print(t1)

tensor([3, 2, 7, 4, 1, 6, 9, 0, 8, 5])


In [112]:
# 查看随机数种子
print(torch.random.initial_seed())

42


In [107]:
torch.manual_seed(42)
