In [1]:
import torch

## 元素类型的转换

In [2]:
t1 = torch.tensor([10, 20])
print(t1.dtype)

torch.int64


In [4]:
# type 方法
t2 = t1.type(torch.float32)
print(t2.dtype)

torch.float32


In [5]:
# to 方法
t3 = t1.to(torch.float32)
print(t3.dtype)

torch.float32


In [9]:
# 直接调用类型相关的方法
print(t1.double().dtype)

torch.float64


## tensor => ndarry

In [10]:
import numpy as np

In [14]:
# 内存共享
t1 = torch.tensor([10, 20])
n1 = t1.numpy()
print(n1)
print(type(n1))

t1[0] = 100
print(t1)
print(n1)


[10 20]
<class 'numpy.ndarray'>
tensor([100,  20])
[100  20]


In [26]:
# 不想共享内存
n1 = t1.numpy().copy()
t1[0] = 200
print(n1)

[200  20]


# ndarray => tensor

In [28]:
n1 = np.array([100, 200, 300])

# torch.tensor(n1)
t1 = torch.from_numpy(n1)  # 内存共享
n1[0] = 10
print(t1)

tensor([ 10, 200, 300])


In [29]:
# 不想共享内存
t1 = torch.from_numpy(n1).clone()
n1[0] = 50
print(t1)

tensor([ 10, 200, 300])


## 张量=> 标量

In [35]:
t1 = torch.tensor([[[[10]]]])  # tensor只有一个元素的情况可以转
print(t1.item())

RuntimeError: a Tensor with 2 elements cannot be converted to Scalar