In [2]:
import torch

In [3]:
t1 = torch.tensor([[10, 20, 30], [40, 50, 60]])

## 基本运算

In [6]:
# +
print(t1 + 10)
print(t1.add(10)) # t1不变,返回一个新的tensor
print(t1.add_(10))  # 修改t1
print(t1)


tensor([[20, 30, 40],
        [50, 60, 70]])
tensor([[20, 30, 40],
        [50, 60, 70]])
tensor([[20, 30, 40],
        [50, 60, 70]])
tensor([[20, 30, 40],
        [50, 60, 70]])


## 元素级运算

In [15]:
t1 = torch.tensor([[1, 2, 3], [4, 5, 6]])
t2 = torch.tensor([[10, 20, 30], [40, 50, 60]])


In [16]:
# 张量+张量  对位相加   形状一样或者满足关闭
print(t1 + t2)

tensor([[11, 22, 33],
        [44, 55, 66]])


In [18]:
print(t1 * t2)  # 哈达玛积
print(t1.mul(t2))

tensor([[ 10,  40,  90],
        [160, 250, 360]])
tensor([[ 10,  40,  90],
        [160, 250, 360]])


## 矩阵相乘

In [24]:
t1 = torch.tensor([[1, 2, 3], [4, 5, 6]])
t2 = torch.tensor([[10, 30], [40, 60] , [40, 60]])

In [27]:
print(t1 @ t2)
print(t1.mm(t2))
print(t1.matmul(t2))

tensor([[210, 330],
        [480, 780]])
tensor([[210, 330],
        [480, 780]])
tensor([[210, 330],
        [480, 780]])


In [30]:
t1 = torch.tensor([[[1, 2, 3], [4, 5, 6], [6, 5, 4]], [[3, 2, 1], [3, 2, 1], [3, 2, 1]]])
t2 = torch.tensor([[[1, 2], [3, 4], [5, 6]], [[6, 5], [4, 3], [2, 1]]])

print(t1.shape, t2.shape)

torch.Size([2, 3, 3]) torch.Size([2, 3, 2])


In [33]:
# 最后2个维度满足 矩阵相乘, 其他保持一致
print(t1 @ t2)
# print(t1.mm(t2))  # 只能是矩阵
print(t1.matmul(t2))

tensor([[[22, 28],
         [49, 64],
         [41, 56]],

        [[28, 22],
         [28, 22],
         [28, 22]]])
tensor([[[22, 28],
         [49, 64],
         [41, 56]],

        [[28, 22],
         [28, 22],
         [28, 22]]])


## 统计运算

In [35]:
t1 = torch.randint(1, 10, (2, 3, 4))
print(t1)

tensor([[[3, 4, 2, 4],
         [3, 7, 1, 1],
         [4, 8, 5, 3]],

        [[3, 3, 7, 3],
         [9, 6, 5, 2],
         [9, 4, 9, 3]]])


In [41]:
# 1. sum
print(t1.sum())
print(t1.sum(dim=1))

tensor(108)
tensor(108)


In [44]:
# 2. mean
print(t1.float().mean(dim=0))

tensor([[3.0000, 3.5000, 4.5000, 3.5000],
        [6.0000, 6.5000, 3.0000, 1.5000],
        [6.5000, 6.0000, 7.0000, 3.0000]])


In [46]:
# 3. max/min
print(t1.float().max(dim=0))

torch.return_types.max(
values=tensor([[3., 4., 7., 4.],
        [9., 7., 5., 2.],
        [9., 8., 9., 3.]]),
indices=tensor([[0, 0, 1, 0],
        [1, 0, 1, 1],
        [1, 0, 1, 0]]))


In [48]:
# 4. var
print(t1.float().var(dim=0))

tensor([[ 0.0000,  0.5000, 12.5000,  0.5000],
        [18.0000,  0.5000,  8.0000,  0.5000],
        [12.5000,  8.0000,  8.0000,  0.0000]])


In [59]:
# 5. 去重
print(t1.unique())

tensor([[[3, 4, 2, 4],
         [3, 7, 1, 1],
         [4, 8, 5, 3]],

        [[3, 3, 7, 3],
         [9, 6, 5, 2],
         [9, 4, 9, 3]]])


In [64]:
# 6. 排序: 默认是矩阵的每一行单独排序  ==== dim=2
print(t1.sort(dim=0))

torch.return_types.sort(
values=tensor([[[3, 3, 2, 3],
         [3, 6, 1, 1],
         [4, 4, 5, 3]],

        [[3, 4, 7, 4],
         [9, 7, 5, 2],
         [9, 8, 9, 3]]]),
indices=tensor([[[0, 1, 0, 1],
         [0, 1, 0, 0],
         [0, 1, 0, 0]],

        [[1, 0, 1, 0],
         [1, 0, 1, 1],
         [1, 0, 1, 1]]]))
