In [2]:
import torch

t = torch.randint(0, 10, (2, 5, 4))
print(t)

tensor([[[4, 2, 0, 6],
         [0, 7, 8, 9],
         [1, 5, 5, 7],
         [4, 9, 4, 0],
         [9, 1, 4, 6]],

        [[8, 7, 8, 2],
         [1, 8, 3, 4],
         [1, 8, 9, 1],
         [0, 9, 9, 0],
         [0, 0, 1, 8]]])


## 简单索引

In [3]:
print(t[0][1][1])
print(t[0, 1, 1])

tensor(7)
tensor(7)


In [5]:
print(t[1][1])

tensor([1, 8, 3, 4])


## 范围索引

In [6]:
print(t[1][1:])


tensor([[1, 8, 3, 4],
        [1, 8, 9, 1],
        [0, 9, 9, 0],
        [0, 0, 1, 8]])


In [9]:
print(t[-1, 1:4, 0:3:2])

tensor([[1, 3],
        [1, 9],
        [0, 9]])


## 列表索引

In [12]:
list1 = [0, 1, 1]
list2 = [1, 2, 3]
list3 = [0, 0, 0]
print(t[list1, list2, list3])

tensor([0, 1, 0])


In [13]:
list1 = [[0], [1]]
list2 = [1, 2, 3]
print(t[list1, list2])

tensor([[[0, 7, 8, 9],
         [1, 5, 5, 7],
         [4, 9, 4, 0]],

        [[1, 8, 3, 4],
         [1, 8, 9, 1],
         [0, 9, 9, 0]]])


## 布尔索引

In [18]:
# 取出所有的大于5的值
mask = t > 5
#print(mask)
print(t[mask])
print(t[t > 5])

tensor([6, 7, 8, 9, 7, 9, 9, 6, 8, 7, 8, 8, 8, 9, 9, 9, 8])
tensor([6, 7, 8, 9, 7, 9, 9, 6, 8, 7, 8, 8, 8, 9, 9, 9, 8])


In [21]:
# 取出满足条件的行: 首元素大于5
mask = t[:, :, 0] > 5
print(mask)
print(mask.shape)
print(t[mask])

tensor([[False, False, False, False,  True],
        [ True, False, False, False, False]])
torch.Size([2, 5])
tensor([[9, 1, 4, 6],
        [8, 7, 8, 2]])


In [26]:
# 取出满足条件的列: 首元素大于5
mask = t[:, 0, :] > 5
print(mask)
print(t.mT[mask].mT)

tensor([[False, False, False,  True],
        [ True,  True,  True, False]])
tensor([[6, 8, 7, 8],
        [9, 1, 8, 3],
        [7, 1, 8, 9],
        [0, 0, 9, 9],
        [6, 0, 0, 1]])


In [28]:
# 满足符合条件的矩阵
mask = t[:, 1, 2] > 5
print(mask)
print(t[mask])

tensor([ True, False])
tensor([[[4, 2, 0, 6],
         [0, 7, 8, 9],
         [1, 5, 5, 7],
         [4, 9, 4, 0],
         [9, 1, 4, 6]]])
