In [1]:
import torch

t1 = torch.randint(1, 10, (3, 2, 6))
print(t1)

tensor([[[1, 2, 7, 2, 9, 6],
         [5, 9, 2, 5, 3, 5]],

        [[6, 3, 7, 3, 4, 9],
         [1, 7, 5, 4, 1, 4]],

        [[4, 7, 9, 8, 1, 6],
         [2, 7, 2, 3, 3, 5]]])


## 变换维度

In [3]:
## 转置 本质: 下标交换   1,0,2 => 2,0,1
print(t1.T)
print(t1.mT)  # 只转置最后2个维度

tensor([[[1, 6, 4],
         [5, 1, 2]],

        [[2, 3, 7],
         [9, 7, 7]],

        [[7, 7, 9],
         [2, 5, 2]],

        [[2, 3, 8],
         [5, 4, 3]],

        [[9, 4, 1],
         [3, 1, 3]],

        [[6, 9, 6],
         [5, 4, 5]]])
tensor([[[1, 5],
         [2, 9],
         [7, 2],
         [2, 5],
         [9, 3],
         [6, 5]],

        [[6, 1],
         [3, 7],
         [7, 5],
         [3, 4],
         [4, 1],
         [9, 4]],

        [[4, 2],
         [7, 7],
         [9, 2],
         [8, 3],
         [1, 3],
         [6, 5]]])


In [4]:
# 交换任意2个维度  (1,0,3) => (0,1,3)
t1.transpose(0, 1)

tensor([[[1, 2, 7, 2, 9, 6],
         [6, 3, 7, 3, 4, 9],
         [4, 7, 9, 8, 1, 6]],

        [[5, 9, 2, 5, 3, 5],
         [1, 7, 5, 4, 1, 4],
         [2, 7, 2, 3, 3, 5]]])

In [7]:
# 重新排列所有维度
print(t1.permute(2, 1, 0))

tensor([[[1, 6, 4],
         [5, 1, 2]],

        [[2, 3, 7],
         [9, 7, 7]],

        [[7, 7, 9],
         [2, 5, 2]],

        [[2, 3, 8],
         [5, 4, 3]],

        [[9, 4, 1],
         [3, 1, 3]],

        [[6, 9, 6],
         [5, 4, 5]]])


## 形状变化

In [12]:
## reshape
print(t1.reshape(-1))
print(t1.reshape(1, 2, 3, 6))

tensor([1, 2, 7, 2, 9, 6, 5, 9, 2, 5, 3, 5, 6, 3, 7, 3, 4, 9, 1, 7, 5, 4, 1, 4,
        4, 7, 9, 8, 1, 6, 2, 7, 2, 3, 3, 5])
tensor([[[[[[[[1, 2, 7, 2, 9, 6],
              [5, 9, 2, 5, 3, 5],
              [6, 3, 7, 3, 4, 9]],

             [[1, 7, 5, 4, 1, 4],
              [4, 7, 9, 8, 1, 6],
              [2, 7, 2, 3, 3, 5]]]]]]]])


In [14]:
## view
print(t1.view(-1))
print(t1.view(1, 2, 3, 6))

tensor([1, 2, 7, 2, 9, 6, 5, 9, 2, 5, 3, 5, 6, 3, 7, 3, 4, 9, 1, 7, 5, 4, 1, 4,
        4, 7, 9, 8, 1, 6, 2, 7, 2, 3, 3, 5])
tensor([[[[1, 2, 7, 2, 9, 6],
          [5, 9, 2, 5, 3, 5],
          [6, 3, 7, 3, 4, 9]],

         [[1, 7, 5, 4, 1, 4],
          [4, 7, 9, 8, 1, 6],
          [2, 7, 2, 3, 3, 5]]]])


In [15]:
t2 = t1.mT


In [19]:
print(t2.reshape(-1))

tensor([1, 5, 2, 9, 7, 2, 2, 5, 9, 3, 6, 5, 6, 1, 3, 7, 7, 5, 3, 4, 4, 1, 9, 4,
        4, 2, 7, 7, 9, 2, 8, 3, 1, 3, 6, 5])


In [24]:
#print(t2.view(-1))
print(t1.is_contiguous())
print(t2.is_contiguous())
t2 = t2.contiguous()
print(t2.view(-1))

True
False
tensor([1, 5, 2, 9, 7, 2, 2, 5, 9, 3, 6, 5, 6, 1, 3, 7, 7, 5, 3, 4, 4, 1, 9, 4,
        4, 2, 7, 7, 9, 2, 8, 3, 1, 3, 6, 5])


## 增删维度

In [30]:
t1 = torch.randint(1, 10, (2, 4))
print(t1)

tensor([[2, 2, 8, 5],
        [5, 5, 3, 6]])


In [32]:
## 添加维度
t2 = t1.unsqueeze(dim=2)
print(t2.shape)
print(t2)

torch.Size([2, 4, 1])
tensor([[[2],
         [2],
         [8],
         [5]],

        [[5],
         [5],
         [3],
         [6]]])


In [43]:
# 删除维度  删除为1的那些维度
print(t2.squeeze())

tensor([[2, 2, 8, 5],
        [5, 5, 3, 6]])


In [47]:
t3 = t1.reshape(1, 1, 1, 1, 2, 1, 4)
print(t3)
print(t3.squeeze().shape)

tensor([[[[[[[2, 2, 8, 5]],

            [[5, 5, 3, 6]]]]]]])
torch.Size([2, 4])


## 张量的拼接

In [60]:
t1 = torch.randint(1, 10, (2, 1, 3))
t2 = torch.randint(1, 10, (2, 3, 3))

print(t1)
print(t2)


tensor([[[3, 7, 1]],

        [[8, 9, 3]]])
tensor([[[9, 9, 8],
         [6, 5, 7],
         [3, 3, 8]],

        [[1, 8, 9],
         [2, 5, 8],
         [7, 2, 8]]])


In [59]:
## 拼接  除了堆叠的维度, 其他要一致
t3 = torch.cat((t1, t2), dim=1)
print(t3)


tensor([[[2, 4, 6],
         [2, 8, 8],
         [1, 4, 1],
         [1, 1, 4],
         [3, 5, 8],
         [4, 9, 8]],

        [[9, 2, 3],
         [8, 8, 4],
         [4, 1, 9],
         [1, 1, 1],
         [4, 8, 7],
         [7, 9, 1]]])


In [65]:
## stack
t1 = torch.randint(1, 10, (2, 3, 3))
t2 = torch.randint(1, 10, (2, 3, 3))
t3 = torch.stack((t1, t2), dim=2)  # 先unsqueeze , 然后再cat
print(t3.shape)

torch.Size([2, 3, 2, 3])
