In [9]:
import pandas as pd
import torch
from torch.utils.data import Dataset, TensorDataset, DataLoader

## 自定义数据集

In [2]:
class MyDataset(Dataset):
    def __init__(self, data):
        self.data = data
    def __len__(self):
        return len(self.data)
    def __getitem__(self, idx):
        return self.data[idx]

In [5]:
ds = MyDataset([10, 20, 30, 40, 50])
print(ds)
print(len(ds))
print(ds[0])

5
10


## 内置的TensorDataset

In [8]:
ds = TensorDataset(torch.LongTensor([10, 20, 30, 40, 50]))
        print(len(ds))
        print(ds[0])
        print(ds[1])
        print(ds[2])

5
(tensor(10),)
(tensor(20),)
(tensor(30),)


## DataLoader  数据加载器

In [16]:
x = torch.randn(10, 3)
y = torch.randn(10)
ds = TensorDataset(x, y)

loader = DataLoader(ds, batch_size=3, shuffle=True, drop_last=False)
for input, target in loader:
    print(input, target)
    print(len(input))


tensor([[ 0.1332, -0.5247, -1.0988],
        [ 0.4025, -1.3307, -0.7116],
        [-1.0475, -0.6064, -0.7508]]) tensor([0.1663, 0.7382, 1.7151])
3
tensor([[-1.7503,  0.9299, -0.8977],
        [ 1.0252, -0.0478, -1.1924],
        [ 0.1908,  1.3736, -0.9390]]) tensor([-0.5883, -0.8626,  1.4916])
3
tensor([[-1.3782,  0.5637, -0.7681],
        [-0.2888, -0.0975,  0.0864],
        [ 0.6415,  2.2290,  1.0998]]) tensor([ 1.5988, -0.1444,  1.1940])
3
tensor([[-0.3509,  0.4835, -1.1270]]) tensor([-1.2995])
1


In [15]:
# 查看批次数
print(len(loader))

# 查看数据条数
print(len(ds))

4
10
