In [1]:
## 模型加载

In [2]:
from transformers import AutoModel

C:\Users\22714\.conda\envs\feihu_dl_conda\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


## 远程加载

In [3]:
model = AutoModel.from_pretrained('google-bert/bert-base-chinese')

C:\Users\22714\.conda\envs\feihu_dl_conda\Lib\site-packages\huggingface_hub\file_download.py:138: UserWarning: `huggingface_hub` cache-system uses symlinks by default to efficiently store duplicated files but your machine does not support them in C:\Users\22714\.cache\huggingface\hub\models--google-bert--bert-base-chinese. Caching files will still work but in a degraded version that might require more space on your disk. This warning can be disabled by setting the `HF_HUB_DISABLE_SYMLINKS_WARNING` environment variable. For more details, see https://huggingface.co/docs/huggingface_hub/how-to-cache#limitations.
To support symlinks on Windows, you either need to activate Developer Mode or to run Python as an administrator. In order to activate developer mode, see this article: https://docs.microsoft.com/en-us/windows/apps/get-started/enable-your-device-for-development
  warnings.warn(message)
Loading weights: 100%|██████████| 199/199 [00:00<00:00, 4146.07it/s]
[transformers] BertModel LOA

In [4]:
print(model)

BertModel(
  (embeddings): BertEmbeddings(
    (word_embeddings): Embedding(21128, 768, padding_idx=0)
    (position_embeddings): Embedding(512, 768)
    (token_type_embeddings): Embedding(2, 768)
    (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True, bias=True)
    (dropout): Dropout(p=0.1, inplace=False)
  )
  (encoder): BertEncoder(
    (layer): ModuleList(
      (0-11): 12 x BertLayer(
        (attention): BertAttention(
          (self): BertSelfAttention(
            (query): Linear(in_features=768, out_features=768, bias=True)
            (key): Linear(in_features=768, out_features=768, bias=True)
            (value): Linear(in_features=768, out_features=768, bias=True)
            (dropout): Dropout(p=0.1, inplace=False)
          )
          (output): BertSelfOutput(
            (dense): Linear(in_features=768, out_features=768, bias=True)
            (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True, bias=True)
            (dropout): Dropout(p=

In [27]:
print(model.embeddings.word_embeddings.weight.shape)
print(model.embeddings.token_type_embeddings.weight)

torch.Size([21128, 768])
Parameter containing:
tensor([[ 0.0010,  0.0012, -0.0060,  ...,  0.0441, -0.0023, -0.0003],
        [ 0.0050, -0.0010,  0.0013,  ...,  0.0018,  0.0086, -0.0022]],
       requires_grad=True)


## 本地加载

In [9]:
model = AutoModel.from_pretrained("../data/mybert")

Loading weights: 100%|██████████| 199/199 [00:00<00:00, 3061.55it/s]
[transformers] BertModel LOAD REPORT from: ../data/mybert
Key                                        | Status     |  | 
-------------------------------------------+------------+--+-
cls.seq_relationship.bias                  | UNEXPECTED |  | 
cls.predictions.transform.dense.weight     | UNEXPECTED |  | 
cls.predictions.transform.dense.bias       | UNEXPECTED |  | 
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |  | 
cls.seq_relationship.weight                | UNEXPECTED |  | 
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |  | 
cls.predictions.bias                       | UNEXPECTED |  | 

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.


In [10]:
print(model)

BertModel(
  (embeddings): BertEmbeddings(
    (word_embeddings): Embedding(21128, 768, padding_idx=0)
    (position_embeddings): Embedding(512, 768)
    (token_type_embeddings): Embedding(2, 768)
    (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True, bias=True)
    (dropout): Dropout(p=0.1, inplace=False)
  )
  (encoder): BertEncoder(
    (layer): ModuleList(
      (0-11): 12 x BertLayer(
        (attention): BertAttention(
          (self): BertSelfAttention(
            (query): Linear(in_features=768, out_features=768, bias=True)
            (key): Linear(in_features=768, out_features=768, bias=True)
            (value): Linear(in_features=768, out_features=768, bias=True)
            (dropout): Dropout(p=0.1, inplace=False)
          )
          (output): BertSelfOutput(
            (dense): Linear(in_features=768, out_features=768, bias=True)
            (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True, bias=True)
            (dropout): Dropout(p=

## 模型加载 - 带任务头的模型加载

In [11]:
from transformers import AutoModelForSequenceClassification

In [12]:
model4sc = AutoModelForSequenceClassification.from_pretrained("google-bert/bert-base-chinese")

Loading weights: 100%|██████████| 199/199 [00:00<00:00, 3431.14it/s]
[transformers] BertForSequenceClassification LOAD REPORT from: google-bert/bert-base-chinese
Key                                        | Status     | 
-------------------------------------------+------------+-
cls.seq_relationship.bias                  | UNEXPECTED | 
cls.predictions.transform.dense.weight     | UNEXPECTED | 
cls.predictions.transform.dense.bias       | UNEXPECTED | 
cls.predictions.transform.LayerNorm.weight | UNEXPECTED | 
cls.seq_relationship.weight                | UNEXPECTED | 
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED | 
cls.predictions.bias                       | UNEXPECTED | 
classifier.bias                            | MISSING    | 
classifier.weight                          | MISSING    | 

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from 

In [13]:
print(model4sc)

BertForSequenceClassification(
  (bert): BertModel(
    (embeddings): BertEmbeddings(
      (word_embeddings): Embedding(21128, 768, padding_idx=0)
      (position_embeddings): Embedding(512, 768)
      (token_type_embeddings): Embedding(2, 768)
      (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True, bias=True)
      (dropout): Dropout(p=0.1, inplace=False)
    )
    (encoder): BertEncoder(
      (layer): ModuleList(
        (0-11): 12 x BertLayer(
          (attention): BertAttention(
            (self): BertSelfAttention(
              (query): Linear(in_features=768, out_features=768, bias=True)
              (key): Linear(in_features=768, out_features=768, bias=True)
              (value): Linear(in_features=768, out_features=768, bias=True)
              (dropout): Dropout(p=0.1, inplace=False)
            )
            (output): BertSelfOutput(
              (dense): Linear(in_features=768, out_features=768, bias=True)
              (LayerNorm): LayerNorm((768,),

In [29]:
model4sc = AutoModelForSequenceClassification.from_pretrained("../data/mybert",num_labels=3)
print(model4sc)

Loading weights: 100%|██████████| 199/199 [00:00<00:00, 3553.75it/s]
[transformers] BertForSequenceClassification LOAD REPORT from: ../data/mybert
Key                                        | Status     | 
-------------------------------------------+------------+-
cls.seq_relationship.bias                  | UNEXPECTED | 
cls.predictions.transform.dense.weight     | UNEXPECTED | 
cls.predictions.transform.dense.bias       | UNEXPECTED | 
cls.predictions.transform.LayerNorm.weight | UNEXPECTED | 
cls.seq_relationship.weight                | UNEXPECTED | 
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED | 
cls.predictions.bias                       | UNEXPECTED | 
classifier.bias                            | MISSING    | 
classifier.weight                          | MISSING    | 

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint.

BertForSequenceClassification(
  (bert): BertModel(
    (embeddings): BertEmbeddings(
      (word_embeddings): Embedding(21128, 768, padding_idx=0)
      (position_embeddings): Embedding(512, 768)
      (token_type_embeddings): Embedding(2, 768)
      (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True, bias=True)
      (dropout): Dropout(p=0.1, inplace=False)
    )
    (encoder): BertEncoder(
      (layer): ModuleList(
        (0-11): 12 x BertLayer(
          (attention): BertAttention(
            (self): BertSelfAttention(
              (query): Linear(in_features=768, out_features=768, bias=True)
              (key): Linear(in_features=768, out_features=768, bias=True)
              (value): Linear(in_features=768, out_features=768, bias=True)
              (dropout): Dropout(p=0.1, inplace=False)
            )
            (output): BertSelfOutput(
              (dense): Linear(in_features=768, out_features=768, bias=True)
              (LayerNorm): LayerNorm((768,),

## 模型的前向传播

### 基准模型

In [14]:
import torch

In [30]:
# 定义输入
vocab_size = 1000
N = 32
L = 11
input_ids = torch.randint(vocab_size, size=(N, L))
print(input_ids)

tensor([[522, 490, 167, 391, 762, 919, 517, 416,  96, 235, 941],
        [562, 139, 664, 183, 412, 758, 947, 351, 237, 585, 165],
        [106, 299, 162, 107, 797, 434, 355, 328,  82, 687, 605],
        [503, 606, 915, 719, 875, 488, 962, 329, 364, 898, 379],
        [761, 584, 185, 602, 963, 782, 695,  75, 564, 597, 682],
        [847, 934, 204, 583, 719, 548, 732,  74, 505, 232, 814],
        [972, 658, 531, 615, 123, 169, 109, 647, 735, 564, 712],
        [847, 637, 960, 367, 908, 726, 607, 102, 299, 602, 175],
        [611, 640, 594, 934, 782, 566, 291, 657, 581, 534, 456],
        [813, 785, 790, 603, 395, 904, 912, 832, 963, 791, 921],
        [611, 557, 966, 286, 255, 651, 713, 695, 111,  48, 300],
        [696, 427,  74, 539, 119,  80, 152,  17, 928, 408, 650],
        [ 85, 439, 720, 510, 217, 686, 924, 209,  65,  12, 614],
        [571,   5, 536, 796, 770, 873,  14, 770, 300, 709, 735],
        [633,  43, 496, 467, 400, 927,  88, 957, 966, 664, 386],
        [331, 377, 348, 6

In [31]:
output = model(input_ids)

In [32]:
print(output)

BaseModelOutputWithPoolingAndCrossAttentions(last_hidden_state=tensor([[[ 6.5592e-01,  2.5796e-01,  2.8768e-01,  ...,  1.0166e+00,
          -4.7083e-01, -2.1390e-01],
         [ 3.2043e-01,  2.2778e-01,  1.8250e-01,  ...,  1.7632e+00,
          -6.8653e-01, -2.2509e-01],
         [ 9.5493e-01,  8.4479e-02,  3.5091e-01,  ...,  1.9524e+00,
          -1.1421e-01, -6.0063e-01],
         ...,
         [ 1.7529e-01, -2.7674e-01,  1.6947e-01,  ...,  6.8951e-01,
          -1.2919e-01, -3.2245e-01],
         [ 1.5303e-01, -3.5137e-01, -5.0638e-01,  ...,  1.0518e+00,
           1.5236e-01, -1.9947e-01],
         [ 2.0352e-01, -6.1021e-01, -4.2181e-02,  ...,  1.0945e+00,
           2.6262e-01, -2.8729e-01]],

        [[-4.1005e-01, -8.4297e-02, -6.0093e-02,  ...,  4.6185e-01,
          -3.8589e-01, -1.6118e-01],
         [-2.9554e-01,  1.4448e-02,  2.0108e-01,  ...,  3.7909e-01,
          -3.1544e-03,  3.8943e-01],
         [ 2.8026e-01,  2.4071e-01, -5.1362e-01,  ...,  1.2370e+00,
          -1.

In [19]:
print(output.last_hidden_state.shape) # 最后一层的隐藏状态(词级分类)

torch.Size([32, 11, 768])


In [21]:
print(output.pooler_output.shape)  # pooler_output 是对 last_hidden_state 的第一个token（[CLS] token）的向量进行进一步处理后的结果，专门用于句子级别的分类任务

torch.Size([32, 768])


## 带任务头的模型

In [33]:
output = model4sc(input_ids)
print(output)

SequenceClassifierOutput(loss=None, logits=tensor([[-0.3393, -1.0169, -0.6261],
        [ 0.4133,  0.1792, -0.4538],
        [ 0.0494, -0.3877, -0.0211],
        [ 0.0957, -0.9783, -0.1618],
        [-0.2829, -0.4520, -0.2377],
        [-0.1228, -0.4965, -0.3531],
        [-0.2949,  0.1684, -0.3408],
        [-0.0625, -1.3110, -0.2517],
        [-0.0664, -0.0155, -0.0281],
        [ 0.0222, -0.0719, -0.2485],
        [-0.1844, -1.2058, -0.5762],
        [ 0.2743, -0.9646, -0.4165],
        [ 0.0897, -0.9409, -0.5079],
        [-0.0359, -0.7964, -0.2598],
        [ 0.0747, -1.0339, -0.3905],
        [ 0.0112, -1.0854, -0.4560],
        [ 0.0700, -0.7585, -0.4676],
        [ 0.0511, -0.9312, -0.4780],
        [-0.1697, -0.7600, -0.5346],
        [ 0.0411, -0.9385, -0.6776],
        [-0.0040, -0.6275, -0.1417],
        [-0.2546, -0.4162,  0.1013],
        [ 0.1919, -1.0240, -0.3159],
        [-0.0636, -0.9036, -0.3643],
        [-0.0202, -1.1443, -0.3980],
        [-0.1952, -0.2866, -0.75

In [34]:
print(output.logits.shape) # 逻辑得分,三分类问题

torch.Size([32, 3])


In [35]:
# 传入目标值,自动计算损失值
target = torch.randint(3, size=(N,))
print(target)

tensor([0, 1, 2, 0, 1, 1, 2, 2, 2, 0, 2, 1, 0, 0, 1, 0, 1, 0, 2, 2, 2, 2, 0, 0,
        0, 1, 2, 2, 1, 2, 0, 0])


In [36]:
output = model4sc(input_ids,labels=target)

In [37]:
print(output)

SequenceClassifierOutput(loss=tensor(1.0761, grad_fn=<NllLossBackward0>), logits=tensor([[-0.3393, -1.0169, -0.6261],
        [ 0.4133,  0.1792, -0.4538],
        [ 0.0494, -0.3877, -0.0211],
        [ 0.0957, -0.9783, -0.1618],
        [-0.2829, -0.4520, -0.2377],
        [-0.1228, -0.4965, -0.3531],
        [-0.2949,  0.1684, -0.3408],
        [-0.0625, -1.3110, -0.2517],
        [-0.0664, -0.0155, -0.0281],
        [ 0.0222, -0.0719, -0.2485],
        [-0.1844, -1.2058, -0.5762],
        [ 0.2743, -0.9646, -0.4165],
        [ 0.0897, -0.9409, -0.5079],
        [-0.0359, -0.7964, -0.2598],
        [ 0.0747, -1.0339, -0.3905],
        [ 0.0112, -1.0854, -0.4560],
        [ 0.0700, -0.7585, -0.4676],
        [ 0.0511, -0.9312, -0.4780],
        [-0.1697, -0.7600, -0.5346],
        [ 0.0411, -0.9385, -0.6776],
        [-0.0040, -0.6275, -0.1417],
        [-0.2546, -0.4162,  0.1013],
        [ 0.1919, -1.0240, -0.3159],
        [-0.0636, -0.9036, -0.3643],
        [-0.0202, -1.1443, -0.3

In [39]:
print(output.loss)

tensor(1.0761, grad_fn=<NllLossBackward0>)


In [40]:
output.loss.backward() # 反向传播

In [41]:
print(output.loss)

tensor(1.0761, grad_fn=<NllLossBackward0>)
