In [1]:
import math
import torch

In [2]:
torch.set_printoptions(precision=6,sci_mode=False) # 保留6位小数并且不使用科学计数法
torch.manual_seed(42) # 写死随机数因子

In [3]:
L = 4
dk = 64

In [5]:
# 定义 Q K V 矩阵
Q = torch.randn(L,dk,requires_grad=True) # 保留梯度
K = torch.randn(L,dk)
V = torch.randn(L,dk)

In [6]:
# 1. 计算注意力评分
scores = Q @ K.T / math.sqrt(dk) # 避免评分差距过大softmax后导致其他信息丢失
print(scores)

tensor([[-0.510677,  0.315312, -0.952588, -2.019327],
        [ 1.298041,  0.092512, -0.196551, -0.941998],
        [ 0.076304,  0.011707,  2.304819, -0.132398],
        [ 0.859177,  0.887971,  2.421388, -1.089582]], grad_fn=<DivBackward0>)


In [8]:
# 2. 计算注意力权重
weights = torch.softmax(scores, dim = -1)
print(weights)

tensor([[0.241071, 0.550640, 0.154962, 0.053327],
        [0.613374, 0.183726, 0.137604, 0.065296],
        [0.083090, 0.077892, 0.771579, 0.067439],
        [0.144071, 0.148280, 0.687126, 0.020523]], grad_fn=<SoftmaxBackward0>)


In [9]:
# 3. 计算上下文向量
vectors = weights @ V
print(vectors)

tensor([[-0.172506, -0.454540, -0.023705,  0.385009, -0.742589, -0.306890,
         -0.491569, -0.300678, -0.123825, -0.233904,  0.121160,  0.323811,
          0.241897,  1.116086, -0.300419, -0.053077,  0.791206, -0.725936,
          1.194641,  0.502886,  0.059372, -0.215776,  0.322253,  0.415748,
         -0.774137, -1.440074, -0.025518, -0.106751,  0.005194,  1.192095,
          0.184683,  0.616439, -0.077257, -1.115051, -1.258011, -0.813750,
          0.125120, -0.331030,  0.256598, -1.673046, -0.329096, -0.118575,
          0.686970,  0.551405, -0.701018,  0.001057, -0.650533,  1.185554,
          0.584191, -1.210074, -0.618163, -0.506702, -0.794287, -1.762477,
          0.960248, -0.563541,  0.740728, -0.799263, -0.354187,  1.189225,
          0.168716,  0.593891, -1.042148, -0.370134],
        [ 0.043615, -1.872461, -0.710673, -0.720499, -0.806666, -0.250609,
         -0.324067, -0.255152,  0.180246, -0.535013, -0.218392,  0.363577,
         -0.059723,  1.029716, -0.403027, -0.5

In [10]:
print(vectors.shape)

torch.Size([4, 64])


In [11]:
# 模拟损失,反向传播
vectors.sum().backward()

In [12]:
print(Q.grad)

tensor([[-0.007735,  0.132956,  0.495446,  0.195785,  0.096105, -0.112208,
         -0.130716, -0.048995,  0.064892,  0.276608, -0.422191,  0.403757,
          0.212525,  0.001047,  0.213626,  0.097343, -0.217080, -0.014260,
         -0.209363, -0.454375,  0.124146,  0.492012,  0.033070,  0.201545,
         -0.296226,  0.210339, -0.403469, -0.001916, -0.297361,  0.049268,
         -0.400998, -0.380880,  0.904136, -0.624188,  0.331239, -0.427066,
          0.021971,  0.627486, -0.117735, -0.374411, -0.693280, -0.219241,
         -0.263685, -0.494677,  0.401302, -0.090153, -0.003853, -0.032435,
         -0.116888, -0.223563,  0.063515,  0.610316,  0.086085, -0.040376,
         -0.140487,  0.539895,  0.092984, -0.086358,  0.126449, -0.336061,
         -0.330843,  0.475930,  0.264430,  0.065574],
        [ 0.073129, -0.001896,  0.582823,  0.107340, -0.263432, -0.137729,
         -0.092207,  0.268063, -0.065959,  0.187166, -0.354113,  0.421647,
          0.371336, -0.029803,  0.316291,  0.0