In [5]:
import torch
import torch.nn as nn

linear = nn.Linear(2, 3)

## 常数初始化

In [7]:
print(linear.weight)
#nn.init.zeros_(linear.weight)
nn.init.ones_(linear.weight)
nn.init.constant_(linear.weight, 5)
print(linear.weight)

Parameter containing:
tensor([[1., 1.],
        [1., 1.],
        [1., 1.]], requires_grad=True)
Parameter containing:
tensor([[5., 5.],
        [5., 5.],
        [5., 5.]], requires_grad=True)


## 秩初始化

In [8]:
nn.init.eye_(linear.weight)
print(linear.weight)

Parameter containing:
tensor([[1., 0.],
        [0., 1.],
        [0., 0.]], requires_grad=True)


## 正态分布初始化

In [15]:
nn.init.normal_(linear.weight, mean=0, std=1)
print(linear.weight)

Parameter containing:
tensor([[ 0.3876,  0.7321],
        [ 1.4385,  1.0412],
        [-1.0183, -0.8288]], requires_grad=True)


## 均匀分布初始化

In [29]:
nn.init.uniform_(linear.weight, a=1, b=2)
print(linear.weight)

Parameter containing:
tensor([[1.2894, 1.7684],
        [1.2755, 1.3458],
        [1.1157, 1.1328]], requires_grad=True)


## Xavier 初始化

In [30]:
## 均匀分布
nn.init.xavier_uniform_(linear.weight)
print(linear.weight)

Parameter containing:
tensor([[-0.1110,  0.8921],
        [ 0.2591,  0.6197],
        [-0.9058,  0.4770]], requires_grad=True)


In [31]:
## 正态分布
nn.init.xavier_normal_(linear.weight)
print(linear.weight)

Parameter containing:
tensor([[-0.4201,  0.0723],
        [ 0.0718,  0.1840],
        [ 0.4066,  0.2086]], requires_grad=True)


## He初始化(Kaiming初始化)

In [34]:
## 均匀分布
nn.init.kaiming_uniform_(linear.weight, mode='fan_in', nonlinearity='relu')
print(linear.weight)

## 正态分布
nn.init.kaiming_normal_(linear.weight, mode='fan_in', nonlinearity='relu')
print(linear.weight)

Parameter containing:
tensor([[ 1.0620,  0.3848],
        [ 1.6556,  0.0516],
        [-0.8261, -1.2430]], requires_grad=True)
Parameter containing:
tensor([[ 0.1554, -1.2518],
        [-0.8638,  1.4643],
        [-1.1365,  0.7125]], requires_grad=True)
