# 基本运算和矩阵乘法

In [1]:
import numpy as np


a1 = np.array([[1,2,3],[4,5,6]])
a2 = np.array([[4,5,6],[7,8,9]])
print(a1 + a2)# 相同位的元素进行计算


[[ 5  7  9]
 [11 13 15]]


In [2]:
print(a1 - a2) # 相同位的元素进行计算


[[-3 -3 -3]
 [-3 -3 -3]]


In [3]:
print(a1 * a2)# 相同位的元素进行计算


[[ 4 10 18]
 [28 40 54]]


In [4]:
print(a1 / a2)# 相同位的元素进行计算

[[0.25       0.4        0.5       ]
 [0.57142857 0.625      0.66666667]]


In [5]:
a1 = np.array([[1,2,3],[4,5,6]])

print(a1 + 10) # 对于标量计算 应用到元素级 即每个元素都对标量进行计算

[[11 12 13]
 [14 15 16]]


In [6]:
print(a1 - 10) # 对于标量计算 应用到元素级 即每个元素都对标量进行计算


[[-9 -8 -7]
 [-6 -5 -4]]


In [7]:
print(a1 * 10) # 对于标量计算 应用到元素级 即每个元素都对标量进行计算



[[10 20 30]
 [40 50 60]]


In [8]:
print(a1 / 10) # 对于标量计算 应用到元素级 即每个元素都对标量进行计算

[[0.1 0.2 0.3]
 [0.4 0.5 0.6]]


In [9]:
# 不同形状的数组进行广播计算 两个数组的维度 从右往左 每一位的维度 要么相同 要么其中一个为1
a3 = np.array([[1,2,3],[4,5,6]])  # 2 3
a4 = np.array([[10,11,12]]) # 1 3
print(a3 + a4)

[[11 13 15]
 [14 16 18]]


In [10]:
print(a3 - a4)

[[-9 -9 -9]
 [-6 -6 -6]]


In [11]:
print(a3 * a4)

[[10 22 36]
 [40 55 72]]


In [12]:
print(a3 / a4)

[[0.1        0.18181818 0.25      ]
 [0.4        0.45454545 0.5       ]]


In [13]:
# 以下为广播各种情况
# (1,2) (1,1)  True
# (2,3) (1,3)  True
# (2,3) (1,4)  False
# (5,2) (5,1)  True


In [14]:
a3 = np.array([[1,2,3],[4,5,6]])  # 2 3
a4 = np.array([[10,11]]) # 1 2
print(a3 + a4) # 不满足要求

ValueError: operands could not be broadcast together with shapes (2,3) (1,2) 

In [15]:
# 对位乘法 表示两个数组的形状是完全一致的
# 矩阵乘法 第一个矩阵的列数 必须 等于 第二个 矩阵的行数
# 最终的结果 为左边的行 以及 右边的列数

a1 = np.array([[1,2,3],[4,5,6]])
a2 = np.array([[6],[4],[2]])


print(a1 @ a2)


[[20]
 [56]]
