In [1]:
import torch
import torch.nn as nn

## 全连接层

In [2]:
linear = nn.Linear(3, 4)

In [3]:
print(linear.weight)
print(linear.bias)

Parameter containing:
tensor([[-0.3194, -0.2427,  0.1066],
        [ 0.5713,  0.4579, -0.1824],
        [-0.1954, -0.0383, -0.4173],
        [-0.5297,  0.2955, -0.0259]], requires_grad=True)
Parameter containing:
tensor([-0.0530,  0.1222,  0.5247, -0.5217], requires_grad=True)


## 向前传播

In [5]:
x = torch.tensor([[10,20, 30], [30, 40, 50]]).float()
y = linear.forward(x)  # (*, out_features)   (2, 4)
print(y)


tensor([[ -4.9024,   9.5218, -14.7140,  -0.6878],
        [-14.0125,  26.4586, -27.7332,  -5.8914]], grad_fn=<AddmmBackward0>)


In [6]:
y = linear(x)  # 向前传播
print(y)

tensor([[ -4.9024,   9.5218, -14.7140,  -0.6878],
        [-14.0125,  26.4586, -27.7332,  -5.8914]], grad_fn=<AddmmBackward0>)
