In [3]:
import  torch
import torch.nn as nn
x = torch.tensor([0.7, -1.2, 2.5, 0, -3.1])

## sigmoid

In [4]:
## 1. 直接调用torch的sigmoid函数
y = torch.sigmoid(x)
print(y)

tensor([0.6682, 0.2315, 0.9241, 0.5000, 0.0431])


In [5]:
## 2. 直接调用tensor的sigmoid函数
y = x.sigmoid()
print(y)

tensor([0.6682, 0.2315, 0.9241, 0.5000, 0.0431])


In [6]:
## 3. nn模块定义的Sigmoid类
sigmoid = nn.Sigmoid()
print(sigmoid.forward(x))
print(sigmoid(x))

tensor([0.6682, 0.2315, 0.9241, 0.5000, 0.0431])
tensor([0.6682, 0.2315, 0.9241, 0.5000, 0.0431])


## Tanh双曲正切函数

In [7]:
print(torch.tanh(x))
print(x.tanh())
print(nn.Tanh()(x))

tensor([ 0.6044, -0.8337,  0.9866,  0.0000, -0.9959])
tensor([ 0.6044, -0.8337,  0.9866,  0.0000, -0.9959])
tensor([ 0.6044, -0.8337,  0.9866,  0.0000, -0.9959])


## ReLu

In [8]:
print(torch.relu(x))
print(x.relu())
print(nn.ReLU()(x))

tensor([0.7000, 0.0000, 2.5000, 0.0000, 0.0000])
tensor([0.7000, 0.0000, 2.5000, 0.0000, 0.0000])
tensor([0.7000, 0.0000, 2.5000, 0.0000, 0.0000])


## Softmax

In [9]:
print(torch.softmax(x, dim=-1))
print(x.softmax(dim=-1))
print(nn.Softmax(dim=-1)(x))

tensor([0.1296, 0.0194, 0.7838, 0.0643, 0.0029])
tensor([0.1296, 0.0194, 0.7838, 0.0643, 0.0029])
tensor([0.1296, 0.0194, 0.7838, 0.0643, 0.0029])


## 其他激活函数

In [11]:
print(nn.LeakyReLU()(x))
print(nn.PReLU()(x))
print(nn.RReLU()(x))
print(nn.ELU()(x))
print(nn.SiLU()(x))
print(nn.Softplus()(x))
print(nn.GELU()(x))



tensor([ 0.7000, -0.0120,  2.5000,  0.0000, -0.0310])
tensor([ 0.7000, -0.3000,  2.5000,  0.0000, -0.7750],
       grad_fn=<PreluKernelBackward0>)
tensor([ 0.7000, -0.2249,  2.5000,  0.0000, -0.3978])
tensor([ 0.7000, -0.6988,  2.5000,  0.0000, -0.9550])
tensor([ 0.4677, -0.2778,  2.3104,  0.0000, -0.1336])
tensor([1.1032, 0.2633, 2.5789, 0.6931, 0.0441])
tensor([ 0.5306, -0.1381,  2.4845,  0.0000, -0.0030])
